# Generated by Django 2.2.16 on 2020-11-30 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0013_auto_20200305_1448'),
        ('payment', '0026_auto_20200305_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_city', models.CharField(max_length=50, null=True)),
                ('billing_district', models.CharField(max_length=50, null=True)),
                ('billing_address', models.CharField(max_length=255, null=True)),
                ('id_number', models.CharField(default='66666666-6', max_length=14)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name_1', models.CharField(max_length=255)),
                ('last_name_2', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoletaElectronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(max_length=64)),
                ('receipt_url', models.CharField(max_length=255)),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket', verbose_name='Basket')),
            ],
        ),
    ]
