# Generated by Django 2.2.16 on 2020-12-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_auto_20200305_1448'),
        ('payment', '0027_boletaelectronica_userbillinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbillinginfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userbillinginfo',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket', verbose_name='Basket'),
        ),
    ]
