# Generated by Django 2.2.16 on 2020-12-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_auto_20201218_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaelectronica',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.Basket', verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='userbillinginfo',
            name='id_option',
            field=models.CharField(choices=[('0', 'Rut'), ('1', 'Pasaporte'), ('2', 'Otros')], default='0', max_length=1),
        ),
    ]
