# Generated by Django 2.2.16 on 2021-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20201230_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbillinginfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userbillinginfo',
            name='last_name_1',
        ),
        migrations.RemoveField(
            model_name='userbillinginfo',
            name='last_name_2',
        ),
        migrations.AddField(
            model_name='userbillinginfo',
            name='names',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
