# Generated by Django 2.2.16 on 2021-01-12 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_auto_20210104_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(default=0)),
                ('order_number', models.CharField(default='', max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('error_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
