# Generated by Django 2.2.16 on 2021-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_boletaerrormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbillinginfo',
            name='names',
        ),
        migrations.AddField(
            model_name='userbillinginfo',
            name='first_name',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbillinginfo',
            name='last_name_1',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbillinginfo',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
