# Generated by Django 2.2.16 on 2021-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_auto_20210120_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaelectronica',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boletaelectronica',
            name='emission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='boletaelectronica',
            name='folio',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
