# Generated by Django 2.2.16 on 2021-04-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0037_auto_20210419_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletausdconversion',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='paypalusdconversion',
            options={'ordering': ['-creation_date']},
        ),
    ]
