# Generated by Django 2.2.16 on 2021-04-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0038_auto_20210420_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbillinginfo',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.Basket', unique=True, verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='userbillinginfo',
            name='boleta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.BoletaElectronica'),
        ),
    ]
