# Generated by Django 2.2.23 on 2021-05-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_auto_20210422_1419'),
        ('payment', '0031_sdnfallbackdata'),
    ]

    operations = [
    ]
