# Generated by Django 2.2.23 on 2021-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0040_merge_20210514_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletausdconversion',
            name='clp_to_usd',
            field=models.DecimalField(decimal_places=2, default=750, help_text='Rate used at boleta emission to get the correct CLP from the USDs', max_digits=6),
        ),
    ]
